services:
  postgres:
    image: postgres:16
    container_name: retailpulse_postgres
    environment:
      POSTGRES_DB: retailpulse
      POSTGRES_USER: retailpulse
      POSTGRES_PASSWORD: retailpulse
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: